[package]
name = "movers"
version = "0.1.0"
edition = "2024"

[dependencies]
scraper = "0.23.1"
reqwest = {version = "0.12.12", features = ["blocking", "json"] }
serde_json = "1.0"
fzf-wrapped = "0.1.4"
